#!/bin/bash
#
# Handles uploading of the charm
#
# EXAMPLE:
# set -x
# export PATH=/snap/bin:$PATH
#
# charm whoami
# RET=$?
# if ((RET > 0)); then
#     echo "Not logged into charmstore"
#     exit 1
# fi
#
# rm -rf temp
# mkdir temp
# cd temp
# unzip ../"$CHARM".charm
# URL=$(charm push . cs:~"$NAMESPACE"/"$CHARM" | yq r - url)
#
# if [ "$CHANNEL" != unpublished ]; then
#     charm release "$URL" --channel "$CHANNEL"
# fi
